### ISSUE TITLE
Release wildapp

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#116]
Correct me if I'm wrong maar dit zijn de stappen die nog genomen dienen te worden m.b.t. de wildschade app release:
- [x] @mvarewyck @eadriaensen tekstjes invoegen
- [x] @mvarewyck @eadriaensen issue #115 oplossen
- [x] @SanderDevisscher @eadriaensen issue #96
- [x] @mvarewyck @eadriaensen issue #117 
- [x] @mvarewyck @eadriaensen issue #118 
- [x] @mvarewyck @eadriaensen issue #120 
- [x] @mvarewyck @eadriaensen issue #122
- [x] @mvarewyck @eadriaensen issue #131 
- [x] @mvarewyck @eadriaensen pull request => master met @berthuygens als reviewer
- [x] @berthuygens deployment op UAT
- [x] @SanderDevisscher @jimcasaer finale check
- [x] @berthuygens  deployment online

Houden jullie hier aub bij als er iets is afgewerkt ?

**Comment by SanderDevisscher** [comment]
@mvarewyck @eadriaensen issues zijn gefixt tijd voor pull request :-)

**Comment by SanderDevisscher** [comment]
@jimcasaer kijk jij de app ook nog eens na?

url: https://grofwildjacht-dev.inbo.be/

**Comment by SanderDevisscher** [comment]
@mvarewyck @eadriaensen kijken jullie eens nr issue #120 ?

**Comment by mvarewyck** [comment]
> @mvarewyck @eadriaensen kijken jullie eens nr issue #120 ?

Dit zou ok moeten zijn nu. @SanderDevisscher Bekijk jij nog eens mijn comment daar?

**Comment by SanderDevisscher** [comment]
@mvarewyck ik heb je vraag in #120 doorgegeven aan @jimcasaer.

Zijn je aanpassingen reeds opgenomen in de UAT ? of enkel lokaal ?

**Comment by mvarewyck** [comment]
> @mvarewyck ik heb je vraag in #120 doorgegeven aan @jimcasaer.
> 
> Zijn je aanpassingen reeds opgenomen in de UAT ? of enkel lokaal ?

Enkel lokaal

**Comment by SanderDevisscher** [comment]
De app staat online (https://grofwildjacht.inbo.be/).
Dank je voor jullie inspanningen :-)
